### ISSUE TITLE
请问此项目的授权协议是什么呢？

### ISSUE THREAD

**Issue by QuantumGhost** [MrSong0607/netease-im#1]
如题，在首页上没看到此项目的授权协议

**Comment by MrSong0607** [comment]
谢谢提醒，项目使用GPL协议，已经加到首页了 @QuantumGhost

**Comment by QuantumGhost** [comment]
提醒一下，在 Go 库上面使用 GPL 的话，因为 GPL 的传染性，所有使用这个库的软件和库都会需要以 GPL 的方式开源，所以说是不是能考虑使用别的 license 发布呢？（或者加上 [linking exception](https://en.wikipedia.org/wiki/GPL_linking_exception)）
FYI: [GNU 的解释](https://www.gnu.org/licenses/gpl-faq.html#IfLibraryIsGPL)

**Comment by MrSong0607** [comment]
抱歉，我以为只有修改源码才需要需要以GPL开源，换成MIT好了
